/** 40 pre-baked citizen names for the simulation. */
export const AGENT_NAMES: string[] = [
  "Ada Ironwright",
  "Barnaby Soot",
  "Cecilia Windmere",
  "Dmitri Brassov",
  "Elena Foxglove",
  "Finnegan Cork",
  "Greta Ashdown",
  "Hugo Tidewell",
  "Iris Cobblestone",
  "Jasper Flint",
  "Kira Moonvale",
  "Leopold Crane",
  "Marta Ember",
  "Nikolai Dusk",
  "Ophelia Birch",
  "Percy Goldthwaite",
  "Quinn Ravenshaw",
  "Rosa Steelhand",
  "Silas Thornbury",
  "Tabitha Wren",
  "Ulric Hammerfell",
  "Violet Ashmore",
  "Walter Bridgeford",
  "Xenia Starfall",
  "Yuri Coppermine",
  "Zelda Hearthstone",
  "Amos Blackwell",
  "Blythe Fairweather",
  "Cassius Redoak",
  "Delphine Chalk",
  "Edwin Stonegate",
  "Flora Brightwater",
  "Gideon Rust",
  "Helena Sunridge",
  "Ivan Mortar",
  "Juniper Claye",
  "Knox Warbleton",
  "Liora Deepwell",
  "Magnus Ashford",
  "Nell Sparrowhawk",
];

/** 30 traits organized by category. Each agent gets 3-5 randomly. */
export const TRAIT_POOL = {
  economic: ["industrious", "lazy", "greedy", "generous", "frugal", "extravagant"] as const,
  social: ["gregarious", "reclusive", "charismatic", "bitter", "empathetic", "callous"] as const,
  civic: ["patriotic", "anarchist", "reformist", "traditionalist", "progressive", "apathetic"] as const,
  psychological: ["anxious", "stoic", "optimistic", "paranoid", "contrarian", "sycophantic"] as const,
  ideological: ["capitalist", "socialist", "environmentalist", "militarist", "pacifist", "nostalgic"] as const,
};

export const ALL_TRAITS: string[] = Object.values(TRAIT_POOL).flat();
